version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
http:
    address: '0.0.0.0:3000'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
        debug: true
server:
    command: 'php app.php'
    relay: pipes
metrics:
    address: '127.0.0.1:2112'
